name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: make check
    - name: memory check list
      run: valgrind ./list_test
    - name: memory check map
      run: valgrind ./map_test
